import Link from "next/link";
import { Badge, Card, SectionTitle } from "@/components/ui";
import { listInsights, type AiInsight, type InsightSeverity } from "@/lib/osf/insights";

/**
 * The operational half of AI Insights.
 *
 * /insights was wired only to the marketing analysers, which read ad spend,
 * review volume and the publishing queue. On an account that has not connected
 * ads or reviews yet, eleven of the thirteen have nothing to look at, so the
 * page honestly reported one thing — "your queue is empty" — and looked broken.
 *
 * Meanwhile the WhatsApp and CRM engine was measuring live traffic nobody saw
 * here: leads, stale follow-ups, unanswered buyer questions, site visits
 * requested against site visits completed. Same product, same person asking
 * "what needs my attention?", two engines that never met. This brings the
 * second one onto the page.
 *
 * The numbers are computed in SQL and the model may only re-word them; anything
 * it invents is discarded before it reaches this component. See
 * `sanitiseAiInsights` in lib/osf/insights.
 */

const TONE: Record<InsightSeverity, "bad" | "warn" | "brand" | "good"> = {
  critical: "bad",
  warning: "warn",
  info: "brand",
  success: "good",
};

const RAIL: Record<InsightSeverity, string> = {
  critical: "border-l-bad-500/70",
  warning: "border-l-warn-500/70",
  info: "border-l-brand-500/70",
  success: "border-l-good-500/70",
};

const ORDER: InsightSeverity[] = ["critical", "warning", "info", "success"];

function Row({ insight }: { insight: AiInsight }) {
  return (
    <Card className={`border-l-2 ${RAIL[insight.severity]}`}>
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-[13.5px] font-medium text-mist-100">{insight.title}</span>
        <Badge tone={TONE[insight.severity]}>{insight.severity}</Badge>
        {insight.generated_by_ai && <Badge tone="neutral">AI</Badge>}
        {insight.category && <Badge tone="neutral">{insight.category}</Badge>}
      </div>

      <p className="mt-1.5 text-[12px] leading-relaxed text-mist-300">{insight.description}</p>

      {insight.evidence?.length > 0 && (
        <div className="mt-2.5 flex flex-wrap gap-1.5">
          {insight.evidence.slice(0, 6).map((e, i) => (
            <span
              key={i}
              className="rounded-md border border-ink-700 px-2 py-1 text-[11px] text-mist-300"
              title={e.detail ?? undefined}
            >
              {e.label} <span className="tnum font-medium text-mist-100">{String(e.value)}</span>
            </span>
          ))}
        </div>
      )}

      {insight.recommendation && (
        <p className="mt-2.5 text-[12px] text-mist-200">
          <span className="text-mist-400">Do this: </span>
          {insight.recommendation}
        </p>
      )}

      {insight.action_href && insight.action_label && (
        <Link
          href={insight.action_href}
          className="mt-2.5 inline-block text-[12px] font-medium text-brand-300 hover:text-brand-200"
        >
          {insight.action_label} →
        </Link>
      )}
    </Card>
  );
}

/**
 * How old the stored set may be before this page recomputes it.
 *
 * Nothing else regenerates these — there is no cron, only the refresh button on
 * the WhatsApp insights screen — so without this the page would show whatever
 * was last generated by hand, which for a dashboard is worse than showing
 * nothing. Recomputing costs one model call, so it is bounded to once per
 * window rather than run on every render.
 */
const STALE_AFTER_MS = 15 * 60 * 1000;

export async function OperationsInsights() {
  let insights: AiInsight[] = [];
  try {
    insights = await listInsights();

    const newest = insights.reduce<number>((max, i) => {
      const t = new Date(i.created_at).getTime();
      return Number.isNaN(t) ? max : Math.max(max, t);
    }, 0);

    if (!insights.length || Date.now() - newest > STALE_AFTER_MS) {
      // Imported lazily so a page that never needs to regenerate does not pull
      // the generator — and its provider chain — into this render at all.
      const { generateInsights } = await import("@/lib/osf/insights");
      await generateInsights();
      insights = await listInsights();
    }
  } catch {
    // Supabase unreachable, or the module is not provisioned on this install.
    // The marketing half of the page must still render, so this stays quiet.
    return null;
  }

  const live = insights.filter((i) => !i.is_dismissed);
  if (!live.length) return null;

  live.sort((a, b) => ORDER.indexOf(a.severity) - ORDER.indexOf(b.severity));
  const aiCount = live.filter((i) => i.generated_by_ai).length;

  return (
    <div>
      <SectionTitle
        title="From WhatsApp, the CRM and site visits"
        hint={
          `${live.length} item${live.length === 1 ? "" : "s"}` +
          (aiCount ? ` · ${aiCount} written by the AI analyst` : "") +
          " · numbers measured in the database"
        }
      />
      <div className="space-y-2.5">
        {live.map((i) => (
          <Row key={i.id} insight={i} />
        ))}
      </div>
    </div>
  );
}
